/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package GamePackage.Actions;

import java.util.*;
import java.time.*;



// ----------- << imports@AAAAAAF4OBhDzRm4tOk= >>
// ----------- >>

// ----------- << class.annotations@AAAAAAF4OBhDzRm4tOk= >>
// ----------- >>
public class ActivateLeaderCardAction implements Action {
    @Override
    // ----------- << method.annotations@AAAAAAF4QLWE+DkUwpU= >>
    // ----------- >>
    public void performAction() {
    // ----------- << method.body@AAAAAAF4QLWE+DkUwpU= >>
    // ----------- >>
    }
    /**
    * @param position
    */

    // ----------- << method.annotations@AAAAAAF4Re/Imhgf0lY= >>
    // ----------- >>
    public void performAction(int position) {
    // ----------- << method.body@AAAAAAF4Re/Imhgf0lY= >>
    // ----------- >>
    }
// ----------- << class.extras@AAAAAAF4OBhDzRm4tOk= >>
// ----------- >>
}