/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package Model;

import java.util.*;
import java.time.*;



// ----------- << imports@AAAAAAF4NpLoXXPJR2g= >>
// ----------- >>

// ----------- << class.annotations@AAAAAAF4NpLoXXPJR2g= >>
// ----------- >>
public enum ActionToken {
    MOVEBYTWO,
    MOVEANDSHUFFLE,
    REMOVEGREEN,
    REMOVEPURPLE,
    REMOVEYELLOW,
    REMOVEBLUE;

// ----------- << enum.extras@AAAAAAF4NpLoXXPJR2g= >>
// ----------- >>
}