/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package Model;

import java.util.*;
import java.time.*;


import GamePackage.Game;
// ----------- << imports@AAAAAAF4NpABuXGvooU= >>
// ----------- >>

// ----------- << class.annotations@AAAAAAF4NpABuXGvooU= >>
// ----------- >>
public class LeaderCardsDeck {
    // ----------- << attribute.annotations@AAAAAAF4O6TYIAU5hCQ= >>
    // ----------- >>
    private Stack<LeaderCard> deck[0...16];

    // ----------- << attribute.annotations@AAAAAAF4NpqJPXyhDiQ= >>
    // ----------- >>
    private Set<LeaderCard> deck = new HashSet<>();

    // ----------- << attribute.annotations@AAAAAAF4RYqB3HdSrSk= >>
    // ----------- >>
    private Game ;

    public Stack<LeaderCard> getDeck[0...16]() {
        return deck[0...16];
    }

    public Set<LeaderCard> getDeck() {
        return deck;
    }

    public Game get() {
        return ;
    }

    public void setDeck[0...16](Stack<LeaderCard> deck[0...16]) {
        this.deck[0...16] = deck[0...16];
    }

    public void set(Game ) {
        this. = ;
    }

    public void linkDeck(LeaderCard _deck) {
        if (_deck != null) {
            _deck.unlink();
            _deck.set(this);
            getDeck().add(_deck);
        }
    }

    public void link(Game _) {
        if (_ != null) {
            _.unlink();
            _.set(this);
        }

        unlink();
        set(_);
    }

    public void unlinkDeck(LeaderCard _deck) {
        if (_deck != null) {
            _deck.set(null);
            getDeck().remove(_deck);
        }
    }

    public void unlinkDeck(LeaderCard _deck, Iterator<LeaderCard> it) {
        if (_deck != null) {
            _deck.set(null);
            it.remove();
        }
    }

    public void unlink() {
        if (get() != null) {
            get().set(null);
            set(null);
        }
    }

    // ----------- << method.annotations@AAAAAAF4O6XQiAy8Gis= >>
    // ----------- >>
    private void shuffle() {
    // ----------- << method.body@AAAAAAF4O6XQiAy8Gis= >>
    // ----------- >>
    }
    // ----------- << method.annotations@AAAAAAF4O6ZFkR7PsLI= >>
    // ----------- >>
    public List<LeaderCard> popFour() {
    // ----------- << method.body@AAAAAAF4O6ZFkR7PsLI= >>
    // ----------- >>
    }
    // ----------- << method.annotations@AAAAAAF4O6f9RT9Z7Q4= >>
    // ----------- >>
    public void loadLeaderCards() {
    // ----------- << method.body@AAAAAAF4O6f9RT9Z7Q4= >>
    // ----------- >>
    }
// ----------- << class.extras@AAAAAAF4NpABuXGvooU= >>
// ----------- >>
}