/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package Model;

import java.util.*;
import java.time.*;



// ----------- << imports@AAAAAAF4NpNhNXP4P4U= >>
// ----------- >>

// ----------- << class.annotations@AAAAAAF4NpNhNXP4P4U= >>
// ----------- >>
public enum Resource {
    COIN,
    SERVANT,
    STONE,
    SHIELD;

// ----------- << enum.extras@AAAAAAF4NpNhNXP4P4U= >>
// ----------- >>
}