/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package GamePackage.TurnStates;

import java.util.*;
import java.time.*;



// ----------- << imports@AAAAAAF4N+m6nxO2xEg= >>
// ----------- >>

// ----------- << class.annotations@AAAAAAF4N+m6nxO2xEg= >>
// ----------- >>
public class TakeResource extends AbstractTurnState {
// ----------- << class.extras@AAAAAAF4N+m6nxO2xEg= >>
// ----------- >>
}