/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package it.polimi.ingsw.server.model.gamestates;

import java.util.*;
import java.time.*;



// ----------- << imports@AAAAAAF4PAbPxV1l6eY= >>
// ----------- >>

// ----------- << class.annotations@AAAAAAF4PAbPxV1l6eY= >>
// ----------- >>
public class InGame extends AbstractGameState {
    // ----------- << method.annotations@AAAAAAF4QS/BKaIoVkw= >>
    // ----------- >>
    public void handle() {
    // ----------- << method.body@AAAAAAF4QS/BKaIoVkw= >>
    // ----------- >>
    }
// ----------- << class.extras@AAAAAAF4PAbPxV1l6eY= >>
// ----------- >>
}