/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package it.polimi.ingsw.server.controller.gamestates;


// ----------- << imports@AAAAAAF4QSo6F/THykU= >>
// ----------- >>

// ----------- << class.annotations@AAAAAAF4QSo6F/THykU= >>
// ----------- >>
public class LastRound extends AbstractGameState {
    // ----------- << method.annotations@AAAAAAF4QS/am6X7mRk= >>
    // ----------- >>
    public void handle() {
    // ----------- << method.body@AAAAAAF4QS/am6X7mRk= >>
    // ----------- >>
    }
// ----------- << class.extras@AAAAAAF4QSo6F/THykU= >>
// ----------- >>
}