/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package Model;

import java.util.*;
import java.time.*;



// ----------- << imports@AAAAAAF4O3cBY0pA9CU= >>
// ----------- >>

// ----------- << class.annotations@AAAAAAF4O3cBY0pA9CU= >>
// ----------- >>
public class ConvertLeaderCard extends LeaderCard {
    // ----------- << attribute.annotations@AAAAAAF4O40EqPZgtvE= >>
    // ----------- >>
    private Color requirement1;

    // ----------- << attribute.annotations@AAAAAAF4O42gS/2hu+w= >>
    // ----------- >>
    private Color requirement2;

    // ----------- << attribute.annotations@AAAAAAF4O5c5N4BrT0k= >>
    // ----------- >>
    private Resource convertedResource;

    public Color getRequirement1() {
        return requirement1;
    }

    public Color getRequirement2() {
        return requirement2;
    }

    public Resource getConvertedResource() {
        return convertedResource;
    }

    public void setConvertedResource(Resource convertedResource) {
        this.convertedResource = convertedResource;
    }

    @Override
    // ----------- << method.annotations@AAAAAAF4RjrUDX8u+pU= >>
    // ----------- >>
    public int getVictoryPoints() {
    // ----------- << method.body@AAAAAAF4RjrUDX8u+pU= >>
    // ----------- >>
    }
// ----------- << class.extras@AAAAAAF4O3cBY0pA9CU= >>
// ----------- >>
}