/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package Model;

import java.util.*;
import java.time.*;



// ----------- << imports@AAAAAAF4O3a8A0ZQ5Qs= >>
// ----------- >>

// ----------- << class.annotations@AAAAAAF4O3a8A0ZQ5Qs= >>
// ----------- >>
public class DiscountLeaderCard extends LeaderCard {
    // ----------- << attribute.annotations@AAAAAAF4O47IYwqRaYI= >>
    // ----------- >>
    private Color requirement1;

    // ----------- << attribute.annotations@AAAAAAF4O482nw9/LpY= >>
    // ----------- >>
    private Color requirement2;

    // ----------- << attribute.annotations@AAAAAAF4O5UW0G9dOBQ= >>
    // ----------- >>
    private Resource discountedResource;

    public Color getRequirement1() {
        return requirement1;
    }

    public Color getRequirement2() {
        return requirement2;
    }

    public Resource getDiscountedResource() {
        return discountedResource;
    }

    @Override
    // ----------- << method.annotations@AAAAAAF4RjrUDX8u+pU= >>
    // ----------- >>
    public int getVictoryPoints() {
    // ----------- << method.body@AAAAAAF4RjrUDX8u+pU= >>
    // ----------- >>
    }
// ----------- << class.extras@AAAAAAF4O3a8A0ZQ5Qs= >>
// ----------- >>
}