/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package Model;

import java.util.*;
import java.time.*;



// ----------- << imports@AAAAAAF4O2ySsbHvJ8Q= >>
// ----------- >>

// ----------- << class.annotations@AAAAAAF4O2ySsbHvJ8Q= >>
// ----------- >>
public enum LeaderCardAbility {
    DISCOUNT,
    STORE,
    CONVERT,
    PRODUCE;

// ----------- << enum.extras@AAAAAAF4O2ySsbHvJ8Q= >>
// ----------- >>
}