/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package Model;

import java.util.*;
import java.time.*;


import GamePackage.Game;
import PersonalBoardPackage.PersonalBoard;
// ----------- << imports@AAAAAAF4No9ZTXEHD/Y= >>
// ----------- >>

// ----------- << class.annotations@AAAAAAF4No9ZTXEHD/Y= >>
// ----------- >>
public class Market {
    // ----------- << attribute.annotations@AAAAAAF4O81exZfSunY= >>
    // ----------- >>
    private MarketMarble[][] market[4][3];

    // ----------- << attribute.annotations@AAAAAAF4O932L/vFUOA= >>
    // ----------- >>
    private MarketMarble extraMarble;

    // ----------- << attribute.annotations@AAAAAAF4O+YlI2VPDZ4= >>
    // ----------- >>
    private Market instance;

    // ----------- << attribute.annotations@AAAAAAF4N/lndsOwYZw= >>
    // ----------- >>
    private Game ;

    // ----------- << attribute.annotations@AAAAAAF4O+DtjycKB6M= >>
    // ----------- >>
    private PersonalBoard ;

    // ----------- << attribute.annotations@AAAAAAF4O+GJ9ir16cs= >>
    // ----------- >>
    private PersonalBoard ;

    // ----------- << attribute.annotations@AAAAAAF4RijYv0G/Rk0= >>
    // ----------- >>
    private ResourceBank ;

    // ----------- << attribute.annotations@AAAAAAF4O9kCw+tXQXU= >>
    // ----------- >>
    private MarketMarble ;

    public MarketMarble[][] getMarket[4][3]() {
        return market[4][3];
    }

    public MarketMarble getExtraMarble() {
        return extraMarble;
    }

    private Market getInstance() {
        return instance;
    }

    public Game get() {
        return ;
    }

    public PersonalBoard get() {
        return ;
    }

    public PersonalBoard get() {
        return ;
    }

    public ResourceBank get() {
        return ;
    }

    public MarketMarble get() {
        return ;
    }

    public void setMarket[4][3](MarketMarble[][] market[4][3]) {
        this.market[4][3] = market[4][3];
    }

    public void setExtraMarble(MarketMarble extraMarble) {
        this.extraMarble = extraMarble;
    }

    private void setInstance(Market instance) {
        this.instance = instance;
    }

    public void set(Game ) {
        this. = ;
    }

    public void set(PersonalBoard ) {
        this. = ;
    }

    public void set(PersonalBoard ) {
        this. = ;
    }

    public void set(ResourceBank ) {
        this. = ;
    }

    public void set(MarketMarble ) {
        this. = ;
    }

    public void link(PersonalBoard _) {
        set(_);
    }

    public void link(PersonalBoard _) {
        if (_ != null) {
            _.unlink();
            _.set(this);
        }

        unlink();
        set(_);
    }

    public void link(ResourceBank _) {
        set(_);
    }

    public void link(MarketMarble _) {
        if (_ != null) {
            _.unlink();
            _.set(this);
        }

        unlink();
        set(_);
    }

    public void unlink() {
        set(null);
    }

    public void unlink() {
        if (get() != null) {
            get().set(null);
            set(null);
        }
    }

    public void unlink() {
        set(null);
    }

    public void unlink() {
        if (get() != null) {
            get().set(null);
            set(null);
        }
    }

    /**
    * @param line
    */

    // ----------- << method.annotations@AAAAAAF4O9zlGPNe16E= >>
    // ----------- >>
    public Map<MarketMarble, Integer> chooseRow(int line) {
    // ----------- << method.body@AAAAAAF4O9zlGPNe16E= >>
    // ----------- >>
    }
    /**
    * @param column
    */

    // ----------- << method.annotations@AAAAAAF4O97LkAF2dHI= >>
    // ----------- >>
    public Map<MarketMarble, Integer> chooseColumn(int column) {
    // ----------- << method.body@AAAAAAF4O97LkAF2dHI= >>
    // ----------- >>
    }
    // ----------- << method.annotations@AAAAAAF4O+Z1SmwVbm8= >>
    // ----------- >>
    public Market getInstance() {
    // ----------- << method.body@AAAAAAF4O+Z1SmwVbm8= >>
    // ----------- >>
    }
// ----------- << class.extras@AAAAAAF4No9ZTXEHD/Y= >>
// ----------- >>
}