/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package Model;

import java.util.*;
import java.time.*;


import Resource;
// ----------- << imports@AAAAAAF4RZVIbUASWfk= >>
// ----------- >>

/**
* Crate associations with: LeaderCard, Market, DevelopmentCard, DefaultSlot, Game
*/

// ----------- << class.annotations@AAAAAAF4RZVIbUASWfk= >>
// ----------- >>
public class ResourceBank {
    /**
    * @param request
    */

    // ----------- << method.annotations@AAAAAAF4RZXWKWZMm+s= >>
    // ----------- >>
    public Map<Resource, Integer> getResource(Map<Resource, Integer> request) {
    // ----------- << method.body@AAAAAAF4RZXWKWZMm+s= >>
    // ----------- >>
    }
    /**
    * @param request
    */

    // ----------- << method.annotations@AAAAAAF4RZk4QXYA3Vc= >>
    // ----------- >>
    public Resource getResource(Resource request) {
    // ----------- << method.body@AAAAAAF4RZk4QXYA3Vc= >>
    // ----------- >>
    }
    /**
    * @param request
    */

    // ----------- << method.annotations@AAAAAAF4RZ5N1ZE7kjE= >>
    // ----------- >>
    public Map<Resource, Integer> getResource(Map<MarketMarble, Integer> request) {
    // ----------- << method.body@AAAAAAF4RZ5N1ZE7kjE= >>
    // ----------- >>
    }
// ----------- << class.extras@AAAAAAF4RZVIbUASWfk= >>
// ----------- >>
}