/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package it.polimi.ingsw.server.model.gamepackage.singleplayeractions;

import java.util.*;
import java.time.*;
import it.polimi.ingsw.server.model.Color;
import it.polimi.ingsw.server.model.gamepackage.actions.Action;

// ----------- << imports@AAAAAAF4OBiSVR0qvNc= >>
// ----------- >>

// ----------- << class.annotations@AAAAAAF4OBiSVR0qvNc= >>
// ----------- >>
public class DiscardDevelopmentCardsAction implements Action {
    @Override
    // ----------- << method.annotations@AAAAAAF4QLWE+DkUwpU= >>
    // ----------- >>
    public void performAction() {
    // ----------- << method.body@AAAAAAF4QLWE+DkUwpU= >>
    // ----------- >>
    }
    /**
    * @param color
    */

    // ----------- << method.annotations@AAAAAAF4SlpproWG7zg= >>
    // ----------- >>
    public void performAction(Color color) {
    // ----------- << method.body@AAAAAAF4SlpproWG7zg= >>
    // ----------- >>
    }
// ----------- << class.extras@AAAAAAF4OBiSVR0qvNc= >>
// ----------- >>
}