/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package PersonalBoardPackage;

import java.util.*;
import java.time.*;


import StorageElement;
// ----------- << imports@AAAAAAF4NpED0XKe0hs= >>
// ----------- >>

// ----------- << class.annotations@AAAAAAF4NpED0XKe0hs= >>
// ----------- >>
public class Strongbox implements StorageElement {
    // ----------- << attribute.annotations@AAAAAAF4QORetWGR1Ss= >>
    // ----------- >>
    private Map<Risource, Integer> storedResources;

    // ----------- << attribute.annotations@AAAAAAF4Np5NaZMuRSU= >>
    // ----------- >>
    private PersonalBoard ;

    public Map<Risource, Integer> getStoredResources() {
        return storedResources;
    }

    public PersonalBoard get() {
        return ;
    }

    public void set(PersonalBoard ) {
        this. = ;
    }

    public void link(PersonalBoard _) {
        if (_ != null) {
            _.unlinkStrongBox();
            _.setStrongBox(this);
        }

        unlink();
        set(_);
    }

    public void unlink() {
        if (get() != null) {
            get().setStrongBox(null);
            set(null);
        }
    }

    /**
    * @param addResources
    */

    @Override
    // ----------- << method.annotations@AAAAAAF4QPT2TgKZhMk= >>
    // ----------- >>
    public void storeResources(Map<Resource, Integer> addResources) {
    // ----------- << method.body@AAAAAAF4QPT2TgKZhMk= >>
    // ----------- >>
    }
    /**
    * @param delResources
    */

    @Override
    // ----------- << method.annotations@AAAAAAF4QO4kRv4sop0= >>
    // ----------- >>
    public void discardResources(Map<Resource, Integer> delResources) {
    // ----------- << method.body@AAAAAAF4QO4kRv4sop0= >>
    // ----------- >>
    }
    // ----------- << method.annotations@AAAAAAF4QmHJQeWRbm4= >>
    // ----------- >>
    public void Operation1() {
    // ----------- << method.body@AAAAAAF4QmHJQeWRbm4= >>
    // ----------- >>
    }
    @Override
    // ----------- << method.annotations@AAAAAAF4Qm08e8UrEEQ= >>
    // ----------- >>
    public Map<Resource, Integer> peekResources() {
    // ----------- << method.body@AAAAAAF4Qm08e8UrEEQ= >>
    // ----------- >>
    }
// ----------- << class.extras@AAAAAAF4NpED0XKe0hs= >>
// ----------- >>
}