/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package GameStates;

import java.util.*;
import java.time.*;



// ----------- << imports@AAAAAAF4PAd0IV9yKUQ= >>
// ----------- >>

// ----------- << class.annotations@AAAAAAF4PAd0IV9yKUQ= >>
// ----------- >>
public class GameFinished extends AbstractGameState {
    // ----------- << method.annotations@AAAAAAF4QS/5R6nOILE= >>
    // ----------- >>
    public void handle() {
    // ----------- << method.body@AAAAAAF4QS/5R6nOILE= >>
    // ----------- >>
    }
    // ----------- << method.annotations@AAAAAAF4RJJcHfbq/L0= >>
    // ----------- >>
    private List<Integer> calculateVictoryPoints() {
    // ----------- << method.body@AAAAAAF4RJJcHfbq/L0= >>
    // ----------- >>
    }
// ----------- << class.extras@AAAAAAF4PAd0IV9yKUQ= >>
// ----------- >>
}