/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package PersonalBoardPackage;

import java.util.*;
import java.time.*;


import VictoryPointsElement;
// ----------- << imports@AAAAAAF4NpFbmHLzM68= >>
// ----------- >>

// ----------- << class.annotations@AAAAAAF4NpFbmHLzM68= >>
// ----------- >>
public class FaithTrack implements VictoryPointsElement {
    // ----------- << attribute.annotations@AAAAAAF4QTkyWk0vSxY= >>
    // ----------- >>
    private int position;

    // ----------- << attribute.annotations@AAAAAAF4QUFgy3mapfU= >>
    // ----------- >>
    private List<boolean> popesFavors;

    // ----------- << attribute.annotations@AAAAAAF4Np7kUZYffbc= >>
    // ----------- >>
    private PersonalBoard ;

    public int getPosition() {
        return position;
    }

    public List<boolean> getPopesFavors() {
        return popesFavors;
    }

    public PersonalBoard get() {
        return ;
    }

    public void set(PersonalBoard ) {
        this. = ;
    }

    @Override
    // ----------- << method.annotations@AAAAAAF4RjrUDX8u+pU= >>
    // ----------- >>
    public int getVictoryPoints() {
    // ----------- << method.body@AAAAAAF4RjrUDX8u+pU= >>
    // ----------- >>
    }
    // ----------- << method.annotations@AAAAAAF4O6Nhw7GqeK0= >>
    // ----------- >>
    public void moveMarker() {
    // ----------- << method.body@AAAAAAF4O6Nhw7GqeK0= >>
    // ----------- >>
    }
    /**
    * @param int
    */

    // ----------- << method.annotations@AAAAAAF4QUAmFnEJIS8= >>
    // ----------- >>
    public void flipPopesFavor(void int) {
    // ----------- << method.body@AAAAAAF4QUAmFnEJIS8= >>
    // ----------- >>
    }
    /**
    * @param position
    */

    // ----------- << method.annotations@AAAAAAF4RYT5u/93RCE= >>
    // ----------- >>
    public FaithTrack(int position) {
    // ----------- << method.body@AAAAAAF4RYT5u/93RCE= >>
    // ----------- >>
    }
// ----------- << class.extras@AAAAAAF4NpFbmHLzM68= >>
// ----------- >>
}