/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package GamePackage;

import java.util.*;
import java.time.*;


import GamePackage.Actions.Action;
import GamePackage.TurnStates.AbstractTurnState;
// ----------- << imports@AAAAAAF4N+hwB++6X8E= >>
// ----------- >>

// ----------- << class.annotations@AAAAAAF4N+hwB++6X8E= >>
// ----------- >>
public class SinglePlayerTurn extends Turn {
    // ----------- << attribute.annotations@AAAAAAF4N/DzH3FQcv8= >>
    // ----------- >>
    private AbstractTurnState ;

    // ----------- << attribute.annotations@AAAAAAF4OB/Z94a7Ddc= >>
    // ----------- >>
    private Action ;

    public AbstractTurnState get() {
        return ;
    }

    public Action get() {
        return ;
    }

    public void set(AbstractTurnState ) {
        this. = ;
    }

    public void set(Action ) {
        this. = ;
    }

    public void link(AbstractTurnState _) {
        set(_);
    }

    public void link(Action _) {
        if (_ != null) {
            _.unlink();
            _.set(this);
        }

        unlink();
        set(_);
    }

    public void unlink() {
        set(null);
    }

    public void unlink() {
        if (get() != null) {
            get().set(null);
            set(null);
        }
    }

    /**
    * @param nextState
    */

    // ----------- << method.annotations@AAAAAAF4RIYojzFn0Nc= >>
    // ----------- >>
    public void setNextState(AbstractTurnState nextState) {
    // ----------- << method.body@AAAAAAF4RIYojzFn0Nc= >>
    // ----------- >>
    }
    // ----------- << method.annotations@AAAAAAF4RJn2CT+UyNQ= >>
    // ----------- >>
    public List<AbstractTurnState> availableNextStates() {
    // ----------- << method.body@AAAAAAF4RJn2CT+UyNQ= >>
    // ----------- >>
    }
// ----------- << class.extras@AAAAAAF4N+hwB++6X8E= >>
// ----------- >>
}