/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package it.polimi.ingsw.server.model.gamepackage.turnstates;

import java.util.*;
import java.time.*;



// ----------- << imports@AAAAAAF4N+mn5hJ7b+8= >>
// ----------- >>

// ----------- << class.annotations@AAAAAAF4N+mn5hJ7b+8= >>
// ----------- >>
public class Start extends AbstractTurnState {
// ----------- << class.extras@AAAAAAF4N+mn5hJ7b+8= >>
// ----------- >>
}