/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package GamePackage.SinglePlayerTurnStates;

import java.util.*;
import java.time.*;


import GamePackage.TurnStates.AbstractTurnState;
// ----------- << imports@AAAAAAF4QTBmatwkim8= >>
// ----------- >>

// ----------- << class.annotations@AAAAAAF4QTBmatwkim8= >>
// ----------- >>
public class ResetAndMove extends AbstractTurnState {
// ----------- << class.extras@AAAAAAF4QTBmatwkim8= >>
// ----------- >>
}