/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package it.polimi.ingsw.server.model.gamepackage;

import java.util.*;
import java.time.*;
import it.polimi.ingsw.server.model.*;
import it.polimi.ingsw.server.model.gamestates.*;

// ----------- << imports@AAAAAAF4No7YsHDaamA= >>
// ----------- >>

// ----------- << class.annotations@AAAAAAF4No7YsHDaamA= >>
// ----------- >>
public class Game {
    // ----------- << attribute.annotations@AAAAAAF4PBaBfCwz7Xs= >>
    // ----------- >>
    private int gameID;

    // ----------- << attribute.annotations@AAAAAAF4PBeNiDrv27M= >>
    // ----------- >>
    private int inkwell;

    // ----------- << attribute.annotations@AAAAAAF4N/jwar3MIgc= >>
    // ----------- >>
    private DevelopmentCardsBoard developmentCardsBoard;

    // ----------- << attribute.annotations@AAAAAAF4N/lndsOvouI= >>
    // ----------- >>
    private Market market;

    // ----------- << attribute.annotations@AAAAAAF4RYqB3HdRJk8= >>
    // ----------- >>
    private LeaderCardsDeck ;

    // ----------- << attribute.annotations@AAAAAAF4RJCjdOZAJ8k= >>
    // ----------- >>
    private ActionTokenDeck actionTokenDeck;

    // ----------- << attribute.annotations@AAAAAAF4PAiuRHFckSs= >>
    // ----------- >>
    private AbstractGameState ;

    // ----------- << attribute.annotations@AAAAAAF4N/NLv4jifSA= >>
    // ----------- >>
    private Turn ;

    public int getGameID() {
        return gameID;
    }

    public int getInkwell() {
        return inkwell;
    }

    public DevelopmentCardsBoard getDevelopmentCardsBoard() {
        return developmentCardsBoard;
    }

    public Market getMarket() {
        return market;
    }

    public LeaderCardsDeck get() {
        return ;
    }

    public ActionTokenDeck getActionTokenDeck() {
        return actionTokenDeck;
    }

    public AbstractGameState get() {
        return ;
    }

    public Turn get() {
        return ;
    }

    public void set(LeaderCardsDeck ) {
        this. = ;
    }

    public void set(AbstractGameState ) {
        this. = ;
    }

    public void set(Turn ) {
        this. = ;
    }

    public void link(LeaderCardsDeck _) {
        if (_ != null) {
            _.unlink();
            _.set(this);
        }

        unlink();
        set(_);
    }

    public void link(AbstractGameState _) {
        set(_);
    }

    public void link(Turn _) {
        if (_ != null) {
            _.unlink();
            _.set(this);
        }

        unlink();
        set(_);
    }

    public void unlink() {
        if (get() != null) {
            get().set(null);
            set(null);
        }
    }

    public void unlink() {
        set(null);
    }

    public void unlink() {
        if (get() != null) {
            get().set(null);
            set(null);
        }
    }

    /**
    * @param nextPlayer
    */

    // ----------- << method.annotations@AAAAAAF4QSrPzAObMM8= >>
    // ----------- >>
    public void nextTurn(Player nextPlayer) {
    // ----------- << method.body@AAAAAAF4QSrPzAObMM8= >>
    // ----------- >>
    }
    /**
    * @param player
    */

    // ----------- << method.annotations@AAAAAAF4RJUx2B5cDRs= >>
    // ----------- >>
    public void moveOtherMarkers(Player player) {
    // ----------- << method.body@AAAAAAF4RJUx2B5cDRs= >>
    // ----------- >>
    }
    /**
    * @param nextState
    */

    // ----------- << method.annotations@AAAAAAF4RYcN0g1IWEU= >>
    // ----------- >>
    public void setNextState(AbstractGameState nextState) {
    // ----------- << method.body@AAAAAAF4RYcN0g1IWEU= >>
    // ----------- >>
    }
    /**
    * @param position
    */

    // ----------- << method.annotations@AAAAAAF4RhUWKF/+b7s= >>
    // ----------- >>
    public void flipOtherPopesFavor(int position) {
    // ----------- << method.body@AAAAAAF4RhUWKF/+b7s= >>
    // ----------- >>
    }
// ----------- << class.extras@AAAAAAF4No7YsHDaamA= >>
// ----------- >>
}