/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package GamePackage;

import java.util.*;
import java.time.*;


import LeaderCard;
import PersonalBoardPackage.PersonalBoard;
// ----------- << imports@AAAAAAF4No+h8XExIUI= >>
// ----------- >>

// ----------- << class.annotations@AAAAAAF4No+h8XExIUI= >>
// ----------- >>
public class Player {
    // ----------- << attribute.annotations@AAAAAAF4PArSSvIbjM0= >>
    // ----------- >>
    private String nickname;

    // ----------- << attribute.annotations@AAAAAAF4RZECCRhEV+k= >>
    // ----------- >>
    private int position;

    // ----------- << attribute.annotations@AAAAAAF4PBP3xZsTjxs= >>
    // ----------- >>
    private PersonalBoard personalBoard;

    // ----------- << attribute.annotations@AAAAAAF4NqCrS7ouS/k= >>
    // ----------- >>
    private Set<LeaderCard> leaderCards = new HashSet<>();

    // ----------- << attribute.annotations@AAAAAAF4NqMPWuURCXE= >>
    // ----------- >>
    private Game ;

    private String getNickname() {
        return nickname;
    }

    public int getPosition() {
        return position;
    }

    public PersonalBoard getPersonalBoard() {
        return personalBoard;
    }

    public Set<LeaderCard> getLeaderCards() {
        return leaderCards;
    }

    public Game get() {
        return ;
    }

    private void setNickname(String nickname) {
        this.nickname = nickname;
    }

    public void set(Game ) {
        this. = ;
    }

    public void linkLeaderCards(LeaderCard _leaderCards) {
        if (_leaderCards != null) {
            getLeaderCards().add(_leaderCards);
        }
    }

    public void unlinkLeaderCards(LeaderCard _leaderCards) {
        if (_leaderCards != null) {
            getLeaderCards().remove(_leaderCards);
        }
    }

    public void unlinkLeaderCards(Iterator<LeaderCard> it) {
        it.remove();
    }

    // ----------- << method.annotations@AAAAAAF4PA32XRfeAHk= >>
    // ----------- >>
    public String getNickname() {
    // ----------- << method.body@AAAAAAF4PA32XRfeAHk= >>
    // ----------- >>
    }
    // ----------- << method.annotations@AAAAAAF4PA6BwSQDMug= >>
    // ----------- >>
    public PersonalBoard getPersonalBoard() {
    // ----------- << method.body@AAAAAAF4PA6BwSQDMug= >>
    // ----------- >>
    }
// ----------- << class.extras@AAAAAAF4No+h8XExIUI= >>
// ----------- >>
}