/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package GamePackage;

import java.util.*;
import java.time.*;


import GamePackage.Actions.Action;
import GamePackage.TurnStates.AbstractTurnState;
// ----------- << imports@AAAAAAF4N+hWLu4rQCY= >>
// ----------- >>

// ----------- << class.annotations@AAAAAAF4N+hWLu4rQCY= >>
// ----------- >>
public class Turn {
    // ----------- << attribute.annotations@AAAAAAF4N/C4dm37UJs= >>
    // ----------- >>
    private AbstractTurnState ;

    // ----------- << attribute.annotations@AAAAAAF4N/NLv4jjL0E= >>
    // ----------- >>
    private Game ;

    // ----------- << attribute.annotations@AAAAAAF4PBSqMr8CozE= >>
    // ----------- >>
    private Player ;

    // ----------- << attribute.annotations@AAAAAAF4OB8CXn0iASs= >>
    // ----------- >>
    private Action ;

    public AbstractTurnState get() {
        return ;
    }

    public Game get() {
        return ;
    }

    public Player get() {
        return ;
    }

    public Action get() {
        return ;
    }

    public void set(AbstractTurnState ) {
        this. = ;
    }

    public void set(Game ) {
        this. = ;
    }

    public void set(Player ) {
        this. = ;
    }

    public void set(Action ) {
        this. = ;
    }

    public void link(AbstractTurnState _) {
        set(_);
    }

    public void link(Game _) {
        if (_ != null) {
            _.unlink();
            _.set(this);
        }

        unlink();
        set(_);
    }

    public void link(Player _) {
        set(_);
    }

    public void link(Action _) {
        if (_ != null) {
            _.unlink();
            _.set(this);
        }

        unlink();
        set(_);
    }

    public void unlink() {
        set(null);
    }

    public void unlink() {
        if (get() != null) {
            get().set(null);
            set(null);
        }
    }

    public void unlink() {
        set(null);
    }

    public void unlink() {
        if (get() != null) {
            get().set(null);
            set(null);
        }
    }

    /**
    * @param nextState
    */

    // ----------- << method.annotations@AAAAAAF4QSseThRVAPg= >>
    // ----------- >>
    public void setNextState(AbstractTurnState nextState) {
    // ----------- << method.body@AAAAAAF4QSseThRVAPg= >>
    // ----------- >>
    }
    // ----------- << method.annotations@AAAAAAF4QStO+xgrO1Y= >>
    // ----------- >>
    public void triggerLastRound() {
    // ----------- << method.body@AAAAAAF4QStO+xgrO1Y= >>
    // ----------- >>
    }
    // ----------- << method.annotations@AAAAAAF4RJkaHzFuxcU= >>
    // ----------- >>
    public List<AbstractTurnState> availableNextStates() {
    // ----------- << method.body@AAAAAAF4RJkaHzFuxcU= >>
    // ----------- >>
    }
// ----------- << class.extras@AAAAAAF4N+hWLu4rQCY= >>
// ----------- >>
}