/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package GamePackage.SinglePlayerActions;

import java.util.*;
import java.time.*;


import GamePackage.Actions.Action;
// ----------- << imports@AAAAAAF4OBilvx7jOG4= >>
// ----------- >>

// ----------- << class.annotations@AAAAAAF4OBilvx7jOG4= >>
// ----------- >>
public class MoveBlackCrossAction implements Action {
    @Override
    // ----------- << method.annotations@AAAAAAF4QLWE+DkUwpU= >>
    // ----------- >>
    public void performAction() {
    // ----------- << method.body@AAAAAAF4QLWE+DkUwpU= >>
    // ----------- >>
    }
// ----------- << class.extras@AAAAAAF4OBilvx7jOG4= >>
// ----------- >>
}