/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package GameStates;

import java.util.*;
import java.time.*;



// ----------- << imports@AAAAAAF4PAabsVtYqyM= >>
// ----------- >>

// ----------- << class.annotations@AAAAAAF4PAabsVtYqyM= >>
// ----------- >>
public class Pregame extends AbstractGameState {
    // ----------- << method.annotations@AAAAAAF4QS+mxp5V4Wc= >>
    // ----------- >>
    public void handle() {
    // ----------- << method.body@AAAAAAF4QS+mxp5V4Wc= >>
    // ----------- >>
    }
    // ----------- << method.annotations@AAAAAAF4RJFJ0+ywvGA= >>
    // ----------- >>
    private void distributeResources() {
    // ----------- << method.body@AAAAAAF4RJFJ0+ywvGA= >>
    // ----------- >>
    }
    // ----------- << method.annotations@AAAAAAF4RJGIF/D7F1M= >>
    // ----------- >>
    private void moveFaithMarkers() {
    // ----------- << method.body@AAAAAAF4RJGIF/D7F1M= >>
    // ----------- >>
    }
// ----------- << class.extras@AAAAAAF4PAabsVtYqyM= >>
// ----------- >>
}