/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package it.polimi.ingsw.server.model.gamepackage.actions;


// ----------- << imports@AAAAAAF4OBup+UMXjiY= >>
// ----------- >>

// ----------- << class.annotations@AAAAAAF4OBup+UMXjiY= >>
// ----------- >>
public interface Action {
    // ----------- << method.annotations@AAAAAAF4QLWE+DkUwpU= >>
    // ----------- >>
    void performAction();
// ----------- << interface.extras@AAAAAAF4OBup+UMXjiY= >>
// ----------- >>
}