/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package it.polimi.ingsw.server.model.gamepackage.actions;

import java.util.*;


// ----------- << imports@AAAAAAF4OBgMdRf/OE8= >>
// ----------- >>

// ----------- << class.annotations@AAAAAAF4OBgMdRf/OE8= >>
// ----------- >>
public class ActivateProductionAction implements Action {
    @Override
    // ----------- << method.annotations@AAAAAAF4QLWE+DkUwpU= >>
    // ----------- >>
    public void performAction() {
    // ----------- << method.body@AAAAAAF4QLWE+DkUwpU= >>
    // ----------- >>
    }
    // ----------- << method.annotations@AAAAAAF4QV1BOMc0zic= >>
    // ----------- >>
    public List<List<boolean>> possibleProductionCombinations() {
    // ----------- << method.body@AAAAAAF4QV1BOMc0zic= >>
    // ----------- >>
    }
    /**
    * @param selectedCombination
    */

    // ----------- << method.annotations@AAAAAAF4QWleMRhO+M8= >>
    // ----------- >>
    public void performAction(List<boolean> selectedCombination) {
    // ----------- << method.body@AAAAAAF4QWleMRhO+M8= >>
    // ----------- >>
    }
    /**
    * @param request
    */

    // ----------- << method.annotations@AAAAAAF4RdCojJDSijA= >>
    // ----------- >>
    private void saveResources(Map<Resource, Integer> request) {
    // ----------- << method.body@AAAAAAF4RdCojJDSijA= >>
    // ----------- >>
    }
// ----------- << class.extras@AAAAAAF4OBgMdRf/OE8= >>
// ----------- >>
}