/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package it.polimi.ingsw.server.model.gamepackage.actions;

import java.util.*;


import Color;
import Level;
// ----------- << imports@AAAAAAF4OBfbvRZG0Tw= >>
// ----------- >>

// ----------- << class.annotations@AAAAAAF4OBfbvRZG0Tw= >>
// ----------- >>
public class BuyDevelopmentCardAction implements Action {
    @Override
    // ----------- << method.annotations@AAAAAAF4QLWE+DkUwpU= >>
    // ----------- >>
    public void performAction() {
    // ----------- << method.body@AAAAAAF4QLWE+DkUwpU= >>
    // ----------- >>
    }
    // ----------- << method.annotations@AAAAAAF4QK/52iOWVrs= >>
    // ----------- >>
    public List<DevelopmentCard> affordableCards() {
    // ----------- << method.body@AAAAAAF4QK/52iOWVrs= >>
    // ----------- >>
    }
    /**
    * @param level 
    * @param color
    */

    // ----------- << method.annotations@AAAAAAF4QLNKZC9clf4= >>
    // ----------- >>
    public void buyDevelopmentCard(Level level, Color color) {
    // ----------- << method.body@AAAAAAF4QLNKZC9clf4= >>
    // ----------- >>
    }
// ----------- << class.extras@AAAAAAF4OBfbvRZG0Tw= >>
// ----------- >>
}