/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package it.polimi.ingsw.server.model.gamepackage.actions;

import java.util.*;


import LeaderCard;
// ----------- << imports@AAAAAAF4OBeq0hSN1Qo= >>
// ----------- >>

// ----------- << class.annotations@AAAAAAF4OBeq0hSN1Qo= >>
// ----------- >>
public class TakeResourceAction implements Action {
    @Override
    // ----------- << method.annotations@AAAAAAF4QLWE+DkUwpU= >>
    // ----------- >>
    public void performAction() {
    // ----------- << method.body@AAAAAAF4QLWE+DkUwpU= >>
    // ----------- >>
    }
    /**
    * @param line
    */

    // ----------- << method.annotations@AAAAAAF4QGpRhyxzahc= >>
    // ----------- >>
    public Map<Resource, Integer> chooseRow(int line) {
    // ----------- << method.body@AAAAAAF4QGpRhyxzahc= >>
    // ----------- >>
    }
    /**
    * @param column
    */

    // ----------- << method.annotations@AAAAAAF4QGphoy7R4rw= >>
    // ----------- >>
    public Map<Resource, Integer> chooseColumn(int column) {
    // ----------- << method.body@AAAAAAF4QGphoy7R4rw= >>
    // ----------- >>
    }
    // ----------- << method.annotations@AAAAAAF4WmZmCLtZOUs= >>
    // ----------- >>
    public LeaderCard chooseLeaderCard() {
    // ----------- << method.body@AAAAAAF4WmZmCLtZOUs= >>
    // ----------- >>
    }
// ----------- << class.extras@AAAAAAF4OBeq0hSN1Qo= >>
// ----------- >>
}