/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package it.polimi.ingsw.server.model;

import java.util.*;
import java.time.*;
import it.polimi.ingsw.server.model.gamepackage.Game;

// ----------- << imports@AAAAAAF4QSwJqSkWtG4= >>
// ----------- >>

// ----------- << class.annotations@AAAAAAF4QSwJqSkWtG4= >>
// ----------- >>
public class ActionTokenDeck {
    // ----------- << attribute.annotations@AAAAAAF4QS0v2EFl6RA= >>
    // ----------- >>
    private Set<ActionToken> fullDeck = new HashSet<>();

    // ----------- << attribute.annotations@AAAAAAF4RJCjdOZBNj8= >>
    // ----------- >>
    private Game ;

    // ----------- << attribute.annotations@AAAAAAF4XDrIVDkbbew= >>
    // ----------- >>
    private Set<ActionToken> currentDeck = new HashSet<>();

    private Set<ActionToken> getFullDeck() {
        return fullDeck;
    }

    public Game get() {
        return ;
    }

    public Set<ActionToken> getCurrentDeck() {
        return currentDeck;
    }

    public void set(Game ) {
        this. = ;
    }

    private void linkFullDeck(ActionToken _fullDeck) {
        if (_fullDeck != null) {
            _fullDeck.unlink();
            _fullDeck.set(this);
            getFullDeck().add(_fullDeck);
        }
    }

    private void unlinkFullDeck(ActionToken _fullDeck) {
        if (_fullDeck != null) {
            _fullDeck.set(null);
            getFullDeck().remove(_fullDeck);
        }
    }

    private void unlinkFullDeck(ActionToken _fullDeck, Iterator<ActionToken> it) {
        if (_fullDeck != null) {
            _fullDeck.set(null);
            it.remove();
        }
    }

    // ----------- << method.annotations@AAAAAAF4QSyr3zVNQ88= >>
    // ----------- >>
    public ActionToken pop() {
    // ----------- << method.body@AAAAAAF4QSyr3zVNQ88= >>
    // ----------- >>
    }
    // ----------- << method.annotations@AAAAAAF4RISn0up7oLM= >>
    // ----------- >>
    public void reset() {
    // ----------- << method.body@AAAAAAF4RISn0up7oLM= >>
    // ----------- >>
    }
    // ----------- << method.annotations@AAAAAAF4QS0Bfjz3Arg= >>
    // ----------- >>
    private void shuffle() {
    // ----------- << method.body@AAAAAAF4QS0Bfjz3Arg= >>
    // ----------- >>
    }
// ----------- << class.extras@AAAAAAF4QSwJqSkWtG4= >>
// ----------- >>
}