/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package it.polimi.ingsw.server.model;

import java.util.*;
import java.time.*;



// ----------- << imports@AAAAAAF4NojUmG6Nd1k= >>
// ----------- >>

// ----------- << class.annotations@AAAAAAF4NojUmG6Nd1k= >>
// ----------- >>
public enum Color {
    GREEN,
    BLUE,
    YELLOW,
    PURPLE;

// ----------- << enum.extras@AAAAAAF4NojUmG6Nd1k= >>
// ----------- >>
}