/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package it.polimi.ingsw.server.model;

import java.util.*;
import java.time.*;



// ----------- << imports@AAAAAAF4N/Tr/o2ll0U= >>
// ----------- >>

// ----------- << class.annotations@AAAAAAF4N/Tr/o2ll0U= >>
// ----------- >>
public class DevelopmentCardsDeck {
    // ----------- << attribute.annotations@AAAAAAF4N/iLk7cahrs= >>
    // ----------- >>
    private Set<DevelopmentCard> deck = new HashSet<>();

    // ----------- << attribute.annotations@AAAAAAF4N/ia5rjP97M= >>
    // ----------- >>
    private DevelopmentCardsBoard ;

    public Set<DevelopmentCard> getDeck() {
        return deck;
    }

    public DevelopmentCardsBoard get() {
        return ;
    }

    public void set(DevelopmentCardsBoard ) {
        this. = ;
    }

    public void linkDeck(DevelopmentCard _deck) {
        if (_deck != null) {
            _deck.unlink();
            _deck.set(this);
            getDeck().add(_deck);
        }
    }

    public void link(DevelopmentCardsBoard _) {
        if (_ != null) {
            _.getBoard[4][3]().add(this);
        }

        unlink();
        set(_);
    }

    public void unlinkDeck(DevelopmentCard _deck) {
        if (_deck != null) {
            _deck.set(null);
            getDeck().remove(_deck);
        }
    }

    public void unlinkDeck(DevelopmentCard _deck, Iterator<DevelopmentCard> it) {
        if (_deck != null) {
            _deck.set(null);
            it.remove();
        }
    }

    public void unlink() {
        if (get() != null) {
            get().getBoard[4][3]().remove(this);
            set(null);
        }
    }

    // ----------- << method.annotations@AAAAAAF4ODHXMfGmDKU= >>
    // ----------- >>
    public DevelopmentCard pop() {
    // ----------- << method.body@AAAAAAF4ODHXMfGmDKU= >>
    // ----------- >>
    }
    // ----------- << method.annotations@AAAAAAF4O134vH8PvN0= >>
    // ----------- >>
    private void shuffle() {
    // ----------- << method.body@AAAAAAF4O134vH8PvN0= >>
    // ----------- >>
    }
    /**
    * @param cards
    */

    // ----------- << method.annotations@AAAAAAF4O2Yxw5ZPAXw= >>
    // ----------- >>
    public DevelopmentCardsDeck(List<DevelopmentCard> cards) {
    // ----------- << method.body@AAAAAAF4O2Yxw5ZPAXw= >>
    // ----------- >>
    }
    // ----------- << method.annotations@AAAAAAF4QMCayZkdh78= >>
    // ----------- >>
    public DevelopmentCard peek() {
    // ----------- << method.body@AAAAAAF4QMCayZkdh78= >>
    // ----------- >>
    }
// ----------- << class.extras@AAAAAAF4N/Tr/o2ll0U= >>
// ----------- >>
}