/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package it.polimi.ingsw.server.model;

import java.util.*;
import java.time.*;



// ----------- << imports@AAAAAAF4NooZsm7Z0PM= >>
// ----------- >>

// ----------- << class.annotations@AAAAAAF4NooZsm7Z0PM= >>
// ----------- >>
public enum Level {
    LEVEL1,
    LEVEL2,
    LEVEL3;

// ----------- << enum.extras@AAAAAAF4NooZsm7Z0PM= >>
// ----------- >>
}