/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package Model;

import java.util.*;
import java.time.*;



// ----------- << imports@AAAAAAF4O9T8ILfSsqM= >>
// ----------- >>

// ----------- << class.annotations@AAAAAAF4O9T8ILfSsqM= >>
// ----------- >>
public enum MarketMarble {
    WHITE,
    RED,
    GREEN,
    BLUE,
    YELLOW,
    PURPLE;

// ----------- << enum.extras@AAAAAAF4O9T8ILfSsqM= >>
// ----------- >>
}