/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package it.polimi.ingsw.server.model;

import java.util.*;
import java.time.*;



// ----------- << imports@AAAAAAF4O3ciS0w4KpM= >>
// ----------- >>

// ----------- << class.annotations@AAAAAAF4O3ciS0w4KpM= >>
// ----------- >>
public class ProduceLeaderCard extends LeaderCard {
    // ----------- << attribute.annotations@AAAAAAF4O4+NCBvnULA= >>
    // ----------- >>
    private Color requirement;

    // ----------- << attribute.annotations@AAAAAAF4O5gfpobl4mM= >>
    // ----------- >>
    private Resource inputResource;

    // ----------- << attribute.annotations@AAAAAAF4RfvVRMxhcc0= >>
    // ----------- >>
    private int faithIncrement;

    // ----------- << attribute.annotations@AAAAAAF4RiWGybvdl+w= >>
    // ----------- >>
    private ResourceBank ;

    public Color getRequirement() {
        return requirement;
    }

    public Resource getInputResource() {
        return inputResource;
    }

    public int getFaithIncrement() {
        return faithIncrement;
    }

    public ResourceBank get() {
        return ;
    }

    public void setInputResource(Resource inputResource) {
        this.inputResource = inputResource;
    }

    public void set(ResourceBank ) {
        this. = ;
    }

    public void link(ResourceBank _) {
        set(_);
    }

    public void unlink() {
        set(null);
    }

    @Override
    // ----------- << method.annotations@AAAAAAF4RjrUDX8u+pU= >>
    // ----------- >>
    public int getVictoryPoints() {
    // ----------- << method.body@AAAAAAF4RjrUDX8u+pU= >>
    // ----------- >>
    }
    /**
    * @param chosenResource
    */

    // ----------- << method.annotations@AAAAAAF4O5h/3YsNbNE= >>
    // ----------- >>
    public Resource produce(Resource chosenResource) {
    // ----------- << method.body@AAAAAAF4O5h/3YsNbNE= >>
    // ----------- >>
    }
// ----------- << class.extras@AAAAAAF4O3ciS0w4KpM= >>
// ----------- >>
}