/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package it.polimi.ingsw.server.model;

import jdk.internal.loader.Resource;

import java.util.*;
import java.time.*;



public class ProduceLeaderCard extends LeaderCard {

    private Color requirement;

    private Resource inputResource;

    private int faithIncrement;

    private ResourceBank ;

    public void setInputResource(Resource inputResource) {
        this.inputResource = inputResource;
    }

    public void set(ResourceBank ) {
        this. = ;
    }

    /**
     * moves on the faith track and produce the chosen resource
    * @param chosenResource
     * @return the produced resource
    */

    public Resource produce(Resource chosenResource) {
        int i = 0;
        while (i<faithIncrement){
            FaithTrack.moveMarker();
        }

        return ResourceBank.getResource(chosenResource);
    }

}