/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package it.polimi.ingsw.server.model;

import java.util.*;
import java.time.*;



// ----------- << imports@AAAAAAF4RjBtCAM0EDo= >>
// ----------- >>

// ----------- << class.annotations@AAAAAAF4RjBtCAM0EDo= >>
// ----------- >>
public interface VictoryPointsElement {
    // ----------- << method.annotations@AAAAAAF4RjrUDX8u+pU= >>
    // ----------- >>
    int getVictoryPoints();
// ----------- << interface.extras@AAAAAAF4RjBtCAM0EDo= >>
// ----------- >>
}