/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package it.polimi.ingsw.server.model.gamepackage.singleplayerturnstates;

import java.util.*;
import java.time.*;
import it.polimi.ingsw.server.model.gamepackage.turnstates.AbstractTurnState;

// ----------- << imports@AAAAAAF4N+qVtRsYs6s= >>
// ----------- >>

// ----------- << class.annotations@AAAAAAF4N+qVtRsYs6s= >>
// ----------- >>
public class MoveBlackCross extends AbstractTurnState {
// ----------- << class.extras@AAAAAAF4N+qVtRsYs6s= >>
// ----------- >>
}