/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package it.polimi.ingsw.server.model.personalboardpackage;

import java.util.*;
import java.time.*;
import it.polimi.ingsw.server.model.ResourceBank;
import it.polimi.ingsw.server.model.Resource;

// ----------- << imports@AAAAAAF4NpHPtHNIq5k= >>
// ----------- >>

// ----------- << class.annotations@AAAAAAF4NpHPtHNIq5k= >>
// ----------- >>
public class DefaultSlot implements DevelopmentSlot {
    // ----------- << attribute.annotations@AAAAAAF4RickpA9tsGI= >>
    // ----------- >>
    private ResourceBank ;

    // ----------- << attribute.annotations@AAAAAAF4RifysCFLZ7c= >>
    // ----------- >>
    private ResourceBank ;

    public ResourceBank get() {
        return ;
    }

    public ResourceBank get() {
        return ;
    }

    public void set(ResourceBank ) {
        this. = ;
    }

    public void set(ResourceBank ) {
        this. = ;
    }

    public void link(ResourceBank _) {
        set(_);
    }

    public void link(ResourceBank _) {
        set(_);
    }

    public void unlink() {
        set(null);
    }

    public void unlink() {
        set(null);
    }

    /**
    * @param resources
    */

    @Override
    // ----------- << method.annotations@AAAAAAF4QTMONjXOrD0= >>
    // ----------- >>
    public Map<Resource, Integer> produce(Map<Resource, Integer> resources) {
    // ----------- << method.body@AAAAAAF4QTMONjXOrD0= >>
    // ----------- >>
    }
// ----------- << class.extras@AAAAAAF4NpHPtHNIq5k= >>
// ----------- >>
}