/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package it.polimi.ingsw.server.model.personalboardpackage;

import java.util.*;
import java.time.*;



// ----------- << imports@AAAAAAF4QTLPDTH7QFo= >>
// ----------- >>

// ----------- << class.annotations@AAAAAAF4QTLPDTH7QFo= >>
// ----------- >>
public interface DevelopmentSlot {
    /**
    * @param resources
    */

    // ----------- << method.annotations@AAAAAAF4QTMONjXOrD0= >>
    // ----------- >>
    Map<Resource, Integer> produce(Map<Resource, Integer> resources);
// ----------- << interface.extras@AAAAAAF4QTLPDTH7QFo= >>
// ----------- >>
}