/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package PersonalBoardPackage;

import java.util.*;
import java.time.*;


import DevelopmentCard;
import GamePackage.Player;
import LeaderCard;
import Market;
import StorageElement;
import VictoryPointsElement;
// ----------- << imports@AAAAAAF4No/AYXFbLkU= >>
// ----------- >>

// ----------- << class.annotations@AAAAAAF4No/AYXFbLkU= >>
// ----------- >>
public class PersonalBoard implements VictoryPointsElement, StorageElement {
    // ----------- << attribute.annotations@AAAAAAF4O+GJ9ir0PR4= >>
    // ----------- >>
    private Market ;

    // ----------- << attribute.annotations@AAAAAAF4QTSvYE+gc08= >>
    // ----------- >>
    private Set<DevelopmentSlot> developmentSlot = new HashSet<>();

    // ----------- << attribute.annotations@AAAAAAF4NqGPUsOSTUQ= >>
    // ----------- >>
    private Set<LeaderCard> leaderCards = new HashSet<>();

    // ----------- << attribute.annotations@AAAAAAF4NqQCKf8fEdw= >>
    // ----------- >>
    private Set<DevelopmentCard> activeDevelopmentCards = new HashSet<>();

    // ----------- << attribute.annotations@AAAAAAF4PBP3xZsUzpM= >>
    // ----------- >>
    private Player ;

    // ----------- << attribute.annotations@AAAAAAF4Np40J5JRdG4= >>
    // ----------- >>
    private WarehouseDepots warehouseDepots;

    // ----------- << attribute.annotations@AAAAAAF4Np5NaZMtb/Y= >>
    // ----------- >>
    private Strongbox strongBox;

    // ----------- << attribute.annotations@AAAAAAF4Np7kUZYeUu8= >>
    // ----------- >>
    private FaithTrack faithTrack;

    public Market get() {
        return ;
    }

    public Set<DevelopmentSlot> getDevelopmentSlot() {
        return developmentSlot;
    }

    public Set<LeaderCard> getLeaderCards() {
        return leaderCards;
    }

    public Set<DevelopmentCard> getActiveDevelopmentCards() {
        return activeDevelopmentCards;
    }

    public Player get() {
        return ;
    }

    public WarehouseDepots getWarehouseDepots() {
        return warehouseDepots;
    }

    public Strongbox getStrongBox() {
        return strongBox;
    }

    public FaithTrack getFaithTrack() {
        return faithTrack;
    }

    public void set(Market ) {
        this. = ;
    }

    public void set(Player ) {
        this. = ;
    }

    public void setWarehouseDepots(WarehouseDepots warehouseDepots) {
        this.warehouseDepots = warehouseDepots;
    }

    public void setStrongBox(Strongbox strongBox) {
        this.strongBox = strongBox;
    }

    public void link(Market _) {
        if (_ != null) {
            _.unlink();
            _.set(this);
        }

        unlink();
        set(_);
    }

    public void linkLeaderCards(LeaderCard _leaderCards) {
        if (_leaderCards != null) {
            getLeaderCards().add(_leaderCards);
        }
    }

    public void linkActiveDevelopmentCards(DevelopmentCard _activeDevelopmentCards) {
        if (_activeDevelopmentCards != null) {
            getActiveDevelopmentCards().add(_activeDevelopmentCards);
        }
    }

    public void linkWarehouseDepots(WarehouseDepots _warehouseDepots) {
        if (_warehouseDepots != null) {
            _warehouseDepots.unlink();
            _warehouseDepots.set(this);
        }

        unlinkWarehouseDepots();
        setWarehouseDepots(_warehouseDepots);
    }

    public void linkStrongBox(Strongbox _strongBox) {
        if (_strongBox != null) {
            _strongBox.unlink();
            _strongBox.set(this);
        }

        unlinkStrongBox();
        setStrongBox(_strongBox);
    }

    public void unlink() {
        if (get() != null) {
            get().set(null);
            set(null);
        }
    }

    public void unlinkLeaderCards(LeaderCard _leaderCards) {
        if (_leaderCards != null) {
            getLeaderCards().remove(_leaderCards);
        }
    }

    public void unlinkLeaderCards(Iterator<LeaderCard> it) {
        it.remove();
    }

    public void unlinkActiveDevelopmentCards(DevelopmentCard _activeDevelopmentCards) {
        if (_activeDevelopmentCards != null) {
            getActiveDevelopmentCards().remove(_activeDevelopmentCards);
        }
    }

    public void unlinkActiveDevelopmentCards(Iterator<DevelopmentCard> it) {
        it.remove();
    }

    public void unlinkWarehouseDepots() {
        if (getWarehouseDepots() != null) {
            getWarehouseDepots().set(null);
            setWarehouseDepots(null);
        }
    }

    public void unlinkStrongBox() {
        if (getStrongBox() != null) {
            getStrongBox().set(null);
            setStrongBox(null);
        }
    }

    @Override
    // ----------- << method.annotations@AAAAAAF4RjrUDX8u+pU= >>
    // ----------- >>
    public int getVictoryPoints() {
    // ----------- << method.body@AAAAAAF4RjrUDX8u+pU= >>
    // ----------- >>
    }
    /**
    * @param addResources
    */

    @Override
    // ----------- << method.annotations@AAAAAAF4Wk109UDSeb8= >>
    // ----------- >>
    public void storeResources(Map<Resource, Integer> addResources) {
    // ----------- << method.body@AAAAAAF4Wk109UDSeb8= >>
    // ----------- >>
    }
    /**
    * @param delResources
    */

    @Override
    // ----------- << method.annotations@AAAAAAF4Wk3BUEnAsZ4= >>
    // ----------- >>
    public void discardResources(Map<Resource, Integer> delResources) {
    // ----------- << method.body@AAAAAAF4Wk3BUEnAsZ4= >>
    // ----------- >>
    }
    @Override
    // ----------- << method.annotations@AAAAAAF4Wk4Ui2QVgjg= >>
    // ----------- >>
    public Map<Resource, Integer> peekResources() {
    // ----------- << method.body@AAAAAAF4Wk4Ui2QVgjg= >>
    // ----------- >>
    }
    /**
    * @param card
    */

    // ----------- << method.annotations@AAAAAAF4QTY3Z7I65n8= >>
    // ----------- >>
    public void discardLeaderCard(LeaderCard card) {
    // ----------- << method.body@AAAAAAF4QTY3Z7I65n8= >>
    // ----------- >>
    }
    /**
    * @param card 
    * @param position
    */

    // ----------- << method.annotations@AAAAAAF4RebhDbspqKc= >>
    // ----------- >>
    public void placeDevelopmentCard(DevelopmentCard card, int position) {
    // ----------- << method.body@AAAAAAF4RebhDbspqKc= >>
    // ----------- >>
    }
    /**
    * @param card
    */

    // ----------- << method.annotations@AAAAAAF4Rekthd6lY+Y= >>
    // ----------- >>
    public List<Boolean> availableDevelopmentCardSlots(DevelopmentCard card) {
    // ----------- << method.body@AAAAAAF4Rekthd6lY+Y= >>
    // ----------- >>
    }
// ----------- << class.extras@AAAAAAF4No/AYXFbLkU= >>
// ----------- >>
}