/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package it.polimi.ingsw.server.model.personalboardpackage;

import java.util.*;
import java.time.*;



// ----------- << imports@AAAAAAF4NpKKlXOfTfQ= >>
// ----------- >>

// ----------- << class.annotations@AAAAAAF4NpKKlXOfTfQ= >>
// ----------- >>
public class SinglePlayerFaithTrack extends FaithTrack {
    // ----------- << attribute.annotations@AAAAAAF4QUNikEjH8fc= >>
    // ----------- >>
    private int blackCrossPosition;

    public int getBlackCrossPosition() {
        return blackCrossPosition;
    }

    // ----------- << method.annotations@AAAAAAF4QUOg0U0Seoc= >>
    // ----------- >>
    public void moveBlackCross() {
    // ----------- << method.body@AAAAAAF4QUOg0U0Seoc= >>
    // ----------- >>
    }
// ----------- << class.extras@AAAAAAF4NpKKlXOfTfQ= >>
// ----------- >>
}