/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package it.polimi.ingsw.server.model.personalboardpackage;

import java.util.*;
import java.time.*;
import it.polimi.ingsw.server.model.*;
// ----------- << imports@AAAAAAF4NpEhsXLIxwg= >>
// ----------- >>

// ----------- << class.annotations@AAAAAAF4NpEhsXLIxwg= >>
// ----------- >>
public class WarehouseDepots implements StorageElement {
    // ----------- << attribute.annotations@AAAAAAF4RbQjYdU+vXw= >>
    // ----------- >>
    private Map<Resource, Integer> resources;

    // ----------- << attribute.annotations@AAAAAAF4Np40J5JSrCw= >>
    // ----------- >>
    private PersonalBoard ;

    private Map<Resource, Integer> getResources() {
        return resources;
    }

    public PersonalBoard get() {
        return ;
    }

    private void setResources(Map<Resource, Integer> resources) {
        this.resources = resources;
    }

    public void set(PersonalBoard ) {
        this. = ;
    }

    public void link(PersonalBoard _) {
        if (_ != null) {
            _.unlinkWarehouseDepots();
            _.setWarehouseDepots(this);
        }

        unlink();
        set(_);
    }

    public void unlink() {
        if (get() != null) {
            get().setWarehouseDepots(null);
            set(null);
        }
    }

    /**
    * @param addResources
    */

    @Override
    // ----------- << method.annotations@AAAAAAF4Wk109UDSeb8= >>
    // ----------- >>
    public void storeResources(Map<Resource, Integer> addResources) {
    // ----------- << method.body@AAAAAAF4Wk109UDSeb8= >>
    // ----------- >>
    }
    /**
    * @param delResources
    */

    @Override
    // ----------- << method.annotations@AAAAAAF4Wk3BUEnAsZ4= >>
    // ----------- >>
    public void discardResources(Map<Resource, Integer> delResources) {
    // ----------- << method.body@AAAAAAF4Wk3BUEnAsZ4= >>
    // ----------- >>
    }
    @Override
    // ----------- << method.annotations@AAAAAAF4Wk4Ui2QVgjg= >>
    // ----------- >>
    public Map<Resource, Integer> peekResources() {
    // ----------- << method.body@AAAAAAF4Wk4Ui2QVgjg= >>
    // ----------- >>
    }
    /**
    * @param resources
    */

    // ----------- << method.annotations@AAAAAAF4QNK519Y5sag= >>
    // ----------- >>
    private boolean canBePlaced(Map<Resource, Integer> resources) {
    // ----------- << method.body@AAAAAAF4QNK519Y5sag= >>
    // ----------- >>
    }
    // ----------- << method.annotations@AAAAAAF4QMchg8NxZsc= >>
    // ----------- >>
    private void arrangeResources() {
    // ----------- << method.body@AAAAAAF4QMchg8NxZsc= >>
    // ----------- >>
    }
    // ----------- << method.annotations@AAAAAAF4QNY7+ekP6+c= >>
    // ----------- >>
    private Map<Resource, Integer> discardableResources() {
    // ----------- << method.body@AAAAAAF4QNY7+ekP6+c= >>
    // ----------- >>
    }
// ----------- << class.extras@AAAAAAF4NpEhsXLIxwg= >>
// ----------- >>
}